/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as ChangelogsRouteRouteImport } from './routes/changelogs/route'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as ChangelogsIndexRouteImport } from './routes/changelogs/index'
import { Route as ChangelogsSplatRouteImport } from './routes/changelogs/$'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogsRouteRoute = ChangelogsRouteRouteImport.update({
  id: '/changelogs',
  path: '/changelogs',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogsIndexRoute = ChangelogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChangelogsRouteRoute,
} as any)
const ChangelogsSplatRoute = ChangelogsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ChangelogsRouteRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelogs': typeof ChangelogsRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/404': typeof R404Route
  '/creator': typeof CreatorRoute
  '/changelogs/$': typeof ChangelogsSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/changelogs/': typeof ChangelogsIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/creator': typeof CreatorRoute
  '/changelogs/$': typeof ChangelogsSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/changelogs': typeof ChangelogsIndexRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelogs': typeof ChangelogsRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/404': typeof R404Route
  '/creator': typeof CreatorRoute
  '/changelogs/$': typeof ChangelogsSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/changelogs/': typeof ChangelogsIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelogs'
    | '/docs'
    | '/404'
    | '/creator'
    | '/changelogs/$'
    | '/docs/$'
    | '/changelogs/'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/creator'
    | '/changelogs/$'
    | '/docs/$'
    | '/changelogs'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/changelogs'
    | '/docs'
    | '/404'
    | '/creator'
    | '/changelogs/$'
    | '/docs/$'
    | '/changelogs/'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogsRouteRoute: typeof ChangelogsRouteRouteWithChildren
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  R404Route: typeof R404Route
  CreatorRoute: typeof CreatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelogs': {
      id: '/changelogs'
      path: '/changelogs'
      fullPath: '/changelogs'
      preLoaderRoute: typeof ChangelogsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelogs/': {
      id: '/changelogs/'
      path: '/'
      fullPath: '/changelogs/'
      preLoaderRoute: typeof ChangelogsIndexRouteImport
      parentRoute: typeof ChangelogsRouteRoute
    }
    '/changelogs/$': {
      id: '/changelogs/$'
      path: '/$'
      fullPath: '/changelogs/$'
      preLoaderRoute: typeof ChangelogsSplatRouteImport
      parentRoute: typeof ChangelogsRouteRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRouteRoute
    }
  }
}

interface ChangelogsRouteRouteChildren {
  ChangelogsSplatRoute: typeof ChangelogsSplatRoute
  ChangelogsIndexRoute: typeof ChangelogsIndexRoute
}

const ChangelogsRouteRouteChildren: ChangelogsRouteRouteChildren = {
  ChangelogsSplatRoute: ChangelogsSplatRoute,
  ChangelogsIndexRoute: ChangelogsIndexRoute,
}

const ChangelogsRouteRouteWithChildren = ChangelogsRouteRoute._addFileChildren(
  ChangelogsRouteRouteChildren,
)

interface DocsRouteRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogsRouteRoute: ChangelogsRouteRouteWithChildren,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  R404Route: R404Route,
  CreatorRoute: CreatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
